### PR TITLE
add Debian based installation

### PR DESCRIPTION
**Pull request by bgruening**
@ThomasWollmann this is a first attempt to use the debian package. This does not include the /web folder as far as I can see ... so maybe we can get this from somewhere else and just copy it in?

If this does not work, I will try to build paraview as conda package, in bioconda we have a build-time for 2h and than we do a conda-install here.

### CODE REVIEW

**Comment by ThomasWollmann** [comment]
Nice idea, but the official package has no Mesa support.

**Comment by ThomasWollmann** [comment]
Maybe a paraview-osmesa superbuild package would be a nice contribution to the imaging community.

**Comment by bgruening** [comment]
@ThomasWollmann the above modification will not work as you need to adjust the pathes in your configs but it outlines how I would do it.

1) base this image ontop of the nginx official one, maybe pinning the version
2) installation via conda

Hope it works!

**Comment by bgruening** [comment]
@ThomasWollmann the rest is nginx configuration I hope.

**Pull request merged**
